version: "3.9"
services:
  frontend:
    build: ./frontend
    container_name: xm-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
  backend:
    build: ./backend/XM-test
    container_name: xm-fake-backend
    restart: always
    ports:
      - "5800:80"
      - "5000:443"
    env_file:
      - ./docker/env/asp.env
    volumes:
      - ./docker/ssl:/https:ro
